#!/usr/bin/env python3
"""
dali_random_read_bin_mpi.py
---------------------------
MPI-enabled random-read benchmark using binary shards generated by create_synthetic_binary.py

This version distributes the workload across multiple nodes/ranks using MPI.
Each rank:
  - Gets an exclusive subset of shards
  - Runs benchmark independently on its local GPUs
  - Reports metrics back to rank 0 for cluster-wide aggregation

Usage:
    mpirun -np 8 -hostfile hosts.txt python dali_random_read_bin_mpi.py \
      --shard "/mnt/weka/shards_64k/*/data.bin" \
      --batch 256 --workers 16 --iterations 10
"""
from __future__ import annotations
import argparse, bisect, glob, json, os, random, sys, time, logging, atexit
from pathlib import Path
from typing import Sequence

import numpy as np
import torch
from nvidia.dali import fn, pipeline_def, types

# Import MPI utilities
sys.path.insert(0, str(Path(__file__).parent.parent))
from mpi_utils import (init_mpi, is_master, gather_metrics, barrier, 
                       get_rank_hostname, assign_shards_to_rank, 
                       setup_rank_logging, print_mpi_info, get_mpi_library_info)
from cluster_stats import aggregate_metrics, format_cluster_report, write_cluster_json

try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False

try:
    from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy
except ImportError:
    from nvidia.dali.plugin.base_iterator import DALIGenericIterator
    from nvidia.dali.plugin.pytorch import LastBatchPolicy

logger = logging.getLogger(__name__)

# Global resource tracking
_open_file_descriptors = []
_pipes = []

def cleanup_resources():
    """Clean up global resources"""
    global _open_file_descriptors, _pipes
    logger.debug("Cleaning up resources...")
    
    for fd in _open_file_descriptors:
        try:
            os.close(fd)
        except Exception as e:
            logger.warning(f"Error closing file descriptor {fd}: {e}")
    _open_file_descriptors.clear()
    _pipes.clear()

atexit.register(cleanup_resources)


# ---------------------------------------------------------------------------
def open_shards(pattern: str, direct: bool):
    """Open shards with proper error handling and resource tracking"""
    try:
        dirs = sorted(Path(p).parent for p in glob.glob(pattern))
        if not dirs:
            raise FileNotFoundError(f"No matches for pattern: {pattern!r}")
        
        logger.debug(f"Found {len(dirs)} shard directories")
        
        flag = os.O_RDONLY | (os.O_DIRECT if direct else 0)
        fds, rec_bytes, cum = [], 0, [0]
        
        for i, d in enumerate(dirs):
            try:
                meta_path = d / "meta.json"
                data_path = d / "data.bin"
                
                if not meta_path.exists():
                    raise FileNotFoundError(f"Missing metadata file: {meta_path}")
                if not data_path.exists():
                    raise FileNotFoundError(f"Missing data file: {data_path}")
                
                with open(meta_path, 'r') as f:
                    meta = json.load(f)
                
                rec_bytes = meta["record_bytes"]
                records = meta["records"]
                
                fd = os.open(data_path, flag)
                fds.append(fd)
                _open_file_descriptors.append(fd)
                
                cum.append(cum[-1] + records)
                logger.debug(f"Opened shard {d}: {records} records, {rec_bytes} bytes each")
                
            except Exception as e:
                logger.error(f"Failed to open shard {d}: {e}")
                for fd in fds:
                    try:
                        os.close(fd)
                        if fd in _open_file_descriptors:
                            _open_file_descriptors.remove(fd)
                    except:
                        pass
                raise
        
        logger.info(f"Successfully opened {len(fds)} shards with {cum[-1]} total records")
        return fds, rec_bytes, cum
        
    except Exception as e:
        logger.error(f"Failed to open shards: {e}")
        raise


# ---------------------------------------------------------------------------
class ExternalIterator:
    def __init__(self, fds, rec_bytes, cum, idx, bs, rank, world):
        self.fds, self.rec_bytes, self.cum = fds, rec_bytes, cum
        s = len(idx)*rank//world; e = len(idx)*(rank+1)//world
        self.idx = idx[s:e];  self.bs = bs;  self.n = len(self.idx); self.i = 0

    def __iter__(self): self.i = 0; return self

    def _fetch(self, g):
        shard = bisect.bisect_right(self.cum, g)-1
        offset = (g - self.cum[shard]) * self.rec_bytes
        buf = os.pread(self.fds[shard], self.rec_bytes, offset)
        return np.frombuffer(buf, np.uint8)

    def __next__(self):
        if self.i >= self.n: raise StopIteration
        batch = [self._fetch(self.idx[(self.i+k)%self.n]) for k in range(self.bs)]
        self.i += self.bs
        return batch

    next = __next__


# ---------------------------------------------------------------------------
@pipeline_def
def pipe(eii):
    tensor = fn.external_source(source=eii, batch=True, dtype=types.UINT8)
    return tensor


# ---------------------------------------------------------------------------
def main():
    try:
        # Parse arguments
        ap = argparse.ArgumentParser(description="MPI-enabled binary random-read benchmark")
        ap.add_argument("--shard", required=True,
            help='glob like "/mnt/weka/shards_64k/*/data.bin"')
        ap.add_argument("--batch", type=int, default=256)
        ap.add_argument("--workers", type=int, default=4)
        ap.add_argument("--shuffle", action="store_true")
        ap.add_argument("--direct", action="store_true", help="O_DIRECT bypass cache")
        ap.add_argument("--device-read-ahead", type=int, default=2,
                        help="DALI prefetch queue depth")
        ap.add_argument("--iterations", type=int, default=1, help="Number of benchmark iterations")
        ap.add_argument("--json-output", type=str, default=None,
                        help="Path to write cluster JSON results (rank 0 only)")
        ap.add_argument("--verbose", "-v", action="store_true", help="Enable verbose logging")
        args = ap.parse_args()

        # Initialize MPI
        comm, rank, world_size = init_mpi()
        setup_rank_logging(rank, verbose=args.verbose)
        
        logger.info(f"Starting MPI benchmark on rank {rank} of {world_size}")
        logger.info(f"Hostname: {get_rank_hostname()}")
        
        # Print MPI info from rank 0
        if is_master(rank):
            print_mpi_info(comm, rank, world_size)
        
        barrier(comm)  # Synchronize before starting
        
        # Discover all shards (same on all ranks)
        all_shard_paths = sorted(glob.glob(args.shard))
        if not all_shard_paths:
            raise FileNotFoundError(f"No shards match pattern: {args.shard}")
        
        logger.info(f"Total shards available: {len(all_shard_paths)}")
        
        # Assign shards to this rank
        my_shard_paths = assign_shards_to_rank(all_shard_paths, rank, world_size)
        logger.info(f"Assigned {len(my_shard_paths)} shards to rank {rank}")
        
        if len(my_shard_paths) == 0:
            logger.warning(f"Rank {rank} has no shards assigned!")
            # Still participate in gather with empty metrics
            local_metrics = {
                'rank': rank,
                'hostname': get_rank_hostname(),
                'gpus': 0,
                'samples_processed': 0,
                'shard_count': 0,
                'iteration_times_ms': [],
                'mean_iteration_ms': 0,
                'std_iteration_ms': 0,
                'min_iteration_ms': 0,
                'max_iteration_ms': 0,
                'median_iteration_ms': 0,
                'throughput_samples_per_s': 0,
                'bandwidth_MiB_s': 0,
                'bandwidth_MB_s': 0
            }
            
            all_metrics = gather_metrics(local_metrics, comm)
            
            if is_master(rank):
                logger.warning("Some ranks had no shards! Check shard distribution.")
            
            sys.exit(0)
        
        # Construct pattern for this rank's shards
        # Open shards assigned to this rank
        my_shard_dirs = [Path(p).parent for p in my_shard_paths]
        
        fds, rec_bytes, cum = [], 0, [0]
        flag = os.O_RDONLY | (os.O_DIRECT if args.direct else 0)
        
        for d in my_shard_dirs:
            meta_path = d / "meta.json"
            data_path = d / "data.bin"
            
            with open(meta_path, 'r') as f:
                meta = json.load(f)
            
            rec_bytes = meta["record_bytes"]
            records = meta["records"]
            
            fd = os.open(data_path, flag)
            fds.append(fd)
            _open_file_descriptors.append(fd)
            cum.append(cum[-1] + records)
        
        total = cum[-1]
        logger.info(f"Loaded {len(fds)} shards with {total} total records")
        
        # Prepare indices (local to this rank)
        idx = list(range(total))
        if args.shuffle:
            random.shuffle(idx)
            logger.info("Shuffled local indices")
        
        # Setup GPU configuration (use local GPUs)
        n_gpu = max(1, torch.cuda.device_count())
        logger.info(f"Using {n_gpu} local GPU(s)")
        
        # Create and build pipes
        pipes = []
        for dev in range(n_gpu):
            eii = ExternalIterator(fds, rec_bytes, cum, idx, args.batch, dev, n_gpu)
            pipe_instance = pipe(batch_size=args.batch,
                               num_threads=args.workers,
                               device_id=dev,
                               prefetch_queue_depth=args.device_read_ahead,
                               eii=eii)
            pipes.append(pipe_instance)
            _pipes.append(pipe_instance)
        
        for p in pipes:
            p.build()
        
        # Create iterator
        it = DALIGenericIterator(pipes, ["record"], size=total,
                                 last_batch_policy=LastBatchPolicy.PARTIAL, dynamic_shape=True)
        
        # Calculate data sizes
        sample_bytes = rec_bytes
        samples_per_iter = args.batch * n_gpu
        bytes_per_iter = sample_bytes * samples_per_iter
        
        logger.info(f"Sample size: {sample_bytes / 1024:.2f} KiB, Samples/iter: {samples_per_iter}")
        
        # Warm-up
        logger.info("Running warm-up...")
        next(it)
        
        # Benchmark iterations
        logger.info(f"Starting benchmark with {args.iterations} iteration(s)...")
        iteration_times_ms = []
        
        for iter_num in range(args.iterations):
            t0 = time.perf_counter()
            
            for batch in next(it):
                for v in batch.values():
                    if hasattr(v, "as_cpu"):
                        v = v.as_cpu()
                    if isinstance(v, torch.Tensor):
                        v = v.cpu()
                    if hasattr(v, "numpy"):
                        _ = v.numpy()
            
            elapsed_ms = (time.perf_counter() - t0) * 1e3
            iteration_times_ms.append(elapsed_ms)
            logger.info(f"  Iteration {iter_num + 1}: {elapsed_ms:.2f} ms")
        
        # Calculate local metrics
        times_array = np.array(iteration_times_ms)
        mean_ms = float(np.mean(times_array))
        std_ms = float(np.std(times_array))
        min_ms = float(np.min(times_array))
        max_ms = float(np.max(times_array))
        median_ms = float(np.median(times_array))
        
        throughput = samples_per_iter / (mean_ms / 1000)
        bandwidth_MiB_s = (bytes_per_iter / (1024**2)) / (mean_ms / 1000)
        bandwidth_MB_s = (bytes_per_iter / (1000**2)) / (mean_ms / 1000)
        
        logger.info(f"Local metrics - Throughput: {throughput:.1f} samples/sec, "
                   f"Bandwidth: {bandwidth_MiB_s:.2f} MiB/s")
        
        # Prepare metrics for gathering
        local_metrics = {
            'rank': rank,
            'hostname': get_rank_hostname(),
            'gpus': n_gpu,
            'samples_processed': total,
            'shard_count': len(my_shard_dirs),
            'iteration_times_ms': iteration_times_ms,
            'mean_iteration_ms': mean_ms,
            'std_iteration_ms': std_ms,
            'min_iteration_ms': min_ms,
            'max_iteration_ms': max_ms,
            'median_iteration_ms': median_ms,
            'throughput_samples_per_s': throughput,
            'bandwidth_MiB_s': bandwidth_MiB_s,
            'bandwidth_MB_s': bandwidth_MB_s
        }
        
        # Gather metrics from all ranks to rank 0
        logger.info("Gathering metrics from all ranks...")
        all_metrics = gather_metrics(local_metrics, comm)
        
        # Rank 0: Aggregate and report
        if is_master(rank):
            logger.info("Aggregating cluster-wide metrics...")
            
            mpi_info = get_mpi_library_info()
            mpi_lib_str = f"{mpi_info.get('library', 'Unknown')} {mpi_info.get('version', '')}"
            
            cluster_metrics = aggregate_metrics(all_metrics, mpi_library=mpi_lib_str)
            
            # Format and print report
            config = {
                'shard': args.shard,
                'batch': args.batch,
                'workers': args.workers,
                'shuffle': args.shuffle,
                'direct': args.direct,
                'device_read_ahead': args.device_read_ahead,
                'iterations': args.iterations,
                'record_bytes': int(rec_bytes)
            }
            
            report = format_cluster_report(cluster_metrics, config)
            print("\n" + report)
            
            # Write JSON output if requested
            if args.json_output:
                write_cluster_json(cluster_metrics, config, args.json_output, 
                                 benchmark_name="binary_random_read_mpi")
                logger.info(f"Wrote cluster results to {args.json_output}")
        
        logger.info(f"Rank {rank} completed successfully")
        
    except KeyboardInterrupt:
        logger.info("Benchmark interrupted by user")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Benchmark failed on rank {rank if 'rank' in locals() else '?'}: {e}")
        import traceback
        logger.error(traceback.format_exc())
        sys.exit(1)
    finally:
        cleanup_resources()


if __name__ == "__main__":
    main()






