#!/usr/bin/env python3
"""
dali_random_read_bin.py
----------------------
Random-read benchmark using binary shards generated by create_synthetic_binary.py
"""
from __future__ import annotations
import argparse, bisect, glob, json, os, random, sys, time, logging, atexit, subprocess
from pathlib import Path
from typing import Sequence

import numpy as np
import torch
from nvidia.dali import fn, pipeline_def, types

try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False

try:
    from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy
except ImportError:
    from nvidia.dali.plugin.base_iterator import DALIGenericIterator
    from nvidia.dali.plugin.pytorch import LastBatchPolicy

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Global resource tracking
_open_file_descriptors = []
_pipes = []

def cleanup_resources():
    """Clean up global resources"""
    global _open_file_descriptors, _pipes
    logger.info("Cleaning up resources...")
    
    # Close file descriptors
    for fd in _open_file_descriptors:
        try:
            os.close(fd)
        except Exception as e:
            logger.warning(f"Error closing file descriptor {fd}: {e}")
    _open_file_descriptors.clear()
    
    # Clear pipe references (DALI manages lifecycle automatically)
    _pipes.clear()
    
    logger.info("Resource cleanup completed")

# Register cleanup function
atexit.register(cleanup_resources)


# ---------------------------------------------------------------------------
def get_memory_stats():
    """Get current memory usage statistics"""
    stats = {}
    
    # System memory
    if HAS_PSUTIL:
        process = psutil.Process(os.getpid())
        mem_info = process.memory_info()
        stats['process_rss_mb'] = mem_info.rss / (1024**2)
        stats['process_vms_mb'] = mem_info.vms / (1024**2)
        
        sys_mem = psutil.virtual_memory()
        stats['system_total_mb'] = sys_mem.total / (1024**2)
        stats['system_used_mb'] = sys_mem.used / (1024**2)
        stats['system_percent'] = sys_mem.percent
    
    # GPU memory
    if torch.cuda.is_available():
        stats['gpu_count'] = torch.cuda.device_count()
        stats['gpu_allocated_mb'] = []
        stats['gpu_reserved_mb'] = []
        stats['gpu_total_mb'] = []
        
        for i in range(torch.cuda.device_count()):
            stats['gpu_allocated_mb'].append(torch.cuda.memory_allocated(i) / (1024**2))
            stats['gpu_reserved_mb'].append(torch.cuda.memory_reserved(i) / (1024**2))
            # Get total memory
            props = torch.cuda.get_device_properties(i)
            stats['gpu_total_mb'].append(props.total_memory / (1024**2))
    
    return stats


def format_memory_stats(stats, label=""):
    """Format memory statistics for logging"""
    lines = []
    if label:
        lines.append(f"{label}:")
    
    if HAS_PSUTIL:
        lines.append(f"  Process RSS:   {stats['process_rss_mb']:.2f} MiB")
        lines.append(f"  System Used:   {stats['system_used_mb']:.2f} / {stats['system_total_mb']:.2f} MiB ({stats['system_percent']:.1f}%)")
    
    if 'gpu_count' in stats and stats['gpu_count'] > 0:
        for i in range(stats['gpu_count']):
            alloc = stats['gpu_allocated_mb'][i]
            reserved = stats['gpu_reserved_mb'][i]
            total = stats['gpu_total_mb'][i]
            lines.append(f"  GPU {i} Memory:  {alloc:.2f} MiB allocated, {reserved:.2f} MiB reserved / {total:.2f} MiB total")
    
    return lines


# ---------------------------------------------------------------------------
def drop_page_cache():
    """
    Drop Linux page cache to measure actual disk performance.
    Requires sudo/root privileges.
    """
    try:
        logger.info("Attempting to drop page cache (requires sudo)...")
        logger.info("  You may be prompted for your password")
        
        # Try to drop page cache
        # sync first to ensure clean state
        subprocess.run(['sudo', 'sync'], check=True)
        subprocess.run(['sudo', 'sh', '-c', 'echo 3 > /proc/sys/vm/drop_caches'], 
                      check=True, capture_output=True, text=True)
        
        logger.info("✓ Page cache dropped successfully")
        logger.info("  Benchmark will now measure actual disk I/O performance")
        return True
        
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to drop page cache: {e}")
        logger.error("  Benchmark will measure cached/memory performance")
        logger.error("  To enable cache dropping, run this script with sudo")
        return False
    except FileNotFoundError:
        logger.error("sudo command not found")
        return False
    except Exception as e:
        logger.error(f"Unexpected error dropping page cache: {e}")
        return False

# ---------------------------------------------------------------------------
def open_shards(pattern: str, direct: bool):
    """Open shards with proper error handling and resource tracking"""
    try:
        dirs = sorted(Path(p).parent for p in glob.glob(pattern))
        if not dirs:
            raise FileNotFoundError(f"No matches for pattern: {pattern!r}")
        
        logger.info(f"Found {len(dirs)} shard directories")
        
        flag = os.O_RDONLY | (os.O_DIRECT if direct else 0)
        fds, rec_bytes, cum = [], 0, [0]
        
        for i, d in enumerate(dirs):
            try:
                logger.debug(f"Opening shard {i+1}/{len(dirs)}: {d}")
                
                # Check for required files
                meta_path = d / "meta.json"
                data_path = d / "data.bin"
                
                if not meta_path.exists():
                    raise FileNotFoundError(f"Missing metadata file: {meta_path}")
                if not data_path.exists():
                    raise FileNotFoundError(f"Missing data file: {data_path}")
                
                # Load metadata
                with open(meta_path, 'r') as f:
                    meta = json.load(f)
                
                rec_bytes = meta["record_bytes"]
                records = meta["records"]
                
                # Open file descriptor
                fd = os.open(data_path, flag)
                fds.append(fd)
                _open_file_descriptors.append(fd)  # Track for cleanup
                
                cum.append(cum[-1] + records)
                logger.debug(f"Opened shard {d}: {records} records, {rec_bytes} bytes each")
                
            except Exception as e:
                logger.error(f"Failed to open shard {d}: {e}")
                # Clean up any opened file descriptors
                for fd in fds:
                    try:
                        os.close(fd)
                        if fd in _open_file_descriptors:
                            _open_file_descriptors.remove(fd)
                    except:
                        pass
                raise
        
        logger.info(f"Successfully opened {len(fds)} shards with {cum[-1]} total records")
        return fds, rec_bytes, cum
        
    except Exception as e:
        logger.error(f"Failed to open shards: {e}")
        raise

# ---------------------------------------------------------------------------
class ExternalIterator:
    def __init__(self, fds, rec_bytes, cum, idx, bs, rank, world):
        self.fds, self.rec_bytes, self.cum = fds, rec_bytes, cum
        s = len(idx)*rank//world; e = len(idx)*(rank+1)//world
        self.idx = idx[s:e];  self.bs = bs;  self.n = len(self.idx); self.i = 0

    def __iter__(self): self.i = 0; return self

    def _fetch(self, g):
        shard = bisect.bisect_right(self.cum, g)-1
        offset = (g - self.cum[shard]) * self.rec_bytes
        buf = os.pread(self.fds[shard], self.rec_bytes, offset)
        return np.frombuffer(buf, np.uint8)              # 64 KiB → (65536,)

    def __next__(self):
        if self.i >= self.n: raise StopIteration
        batch = [self._fetch(self.idx[(self.i+k)%self.n]) for k in range(self.bs)]
        self.i += self.bs
        return batch        

    next = __next__

# ---------------------------------------------------------------------------
@pipeline_def
def pipe(eii):
    tensor = fn.external_source(source=eii, batch=True, dtype=types.UINT8)
    return tensor

# ---------------------------------------------------------------------------
def main():
    try:
        ap = argparse.ArgumentParser()
        ap.add_argument("--shard", required=True,
            help='glob like "/mnt/weka/shards_64k/*/data.bin"')
        ap.add_argument("--batch", type=int, default=256)
        ap.add_argument("--workers", type=int, default=4)
        ap.add_argument("--shuffle", action="store_true")
        ap.add_argument("--direct", action="store_true", help="O_DIRECT bypass cache")
        ap.add_argument("--device-read-ahead", type=int, default=2,
                        help="DALI prefetch queue depth (number of batches prepared in advance, default: 2)")
        ap.add_argument("--iterations", type=int, default=1, help="Number of benchmark iterations")
        ap.add_argument("--drop-cache", action="store_true", 
                        help="Drop page cache before benchmark (requires sudo)")
        ap.add_argument("--verbose", "-v", action="store_true", help="Enable verbose logging")
        args = ap.parse_args()

        # Set logging level based on verbosity
        if args.verbose:
            logging.getLogger().setLevel(logging.DEBUG)

        logger.info(f"Starting benchmark with args: {vars(args)}")
        
        if not HAS_PSUTIL:
            logger.warning("psutil not available, memory stats will be limited")

        # Drop page cache if requested (before loading any data)
        if args.drop_cache:
            drop_page_cache()

        # Open shards with error handling
        fds, rec_bytes, cum = open_shards(args.shard, args.direct)
        total = cum[-1]
        logger.info(f"📦 {len(fds)} shards → {total} samples  "
                   f"(record = {rec_bytes//1024} KiB, O_DIRECT={args.direct})")
        
        # Get initial memory state
        mem_initial = get_memory_stats()
        logger.info("")
        for line in format_memory_stats(mem_initial, "Initial memory usage"):
            logger.info(line)

        # Prepare indices
        idx = list(range(total))
        if args.shuffle: 
            random.shuffle(idx)
            logger.info("Shuffled global indices")

        # Setup GPU configuration
        n_gpu = max(1, torch.cuda.device_count())
        logger.info(f"Using {n_gpu} GPU(s)")

        # Create and build pipes
        pipes = []
        for dev in range(n_gpu):
            try:
                eii = ExternalIterator(fds, rec_bytes, cum, idx, args.batch, dev, n_gpu)
                pipe_instance = pipe(batch_size=args.batch,
                                   num_threads=args.workers,
                                   device_id=dev,
                                   prefetch_queue_depth=args.device_read_ahead,
                                   eii=eii)
                pipes.append(pipe_instance)
                _pipes.append(pipe_instance)  # Track for cleanup
            except Exception as e:
                logger.error(f"Failed to create pipe for GPU {dev}: {e}")
                raise

        # Build all pipes
        for i, p in enumerate(pipes):
            try:
                p.build()
                logger.debug(f"Built pipe {i+1}/{len(pipes)}")
            except Exception as e:
                logger.error(f"Failed to build pipe {i}: {e}")
                raise

        # Create iterator
        it = DALIGenericIterator(pipes, ["record"], size=total,
                                 last_batch_policy=LastBatchPolicy.PARTIAL, dynamic_shape=True)

        # Calculate data sizes for bandwidth metrics
        sample_bytes = rec_bytes
        
        logger.info(f"Sample data size: {sample_bytes / (1024**2):.2f} MiB "
                   f"({sample_bytes / 1024:.2f} KiB per record)")
        
        # Warm-up
        logger.info("Running warm-up...")
        next(it)
        
        # Benchmark iterations
        logger.info(f"Starting benchmark with {args.iterations} iteration(s)...")
        iteration_times_ms = []
        samples_per_iter = args.batch * n_gpu
        bytes_per_iter = sample_bytes * samples_per_iter
        
        # Track peak memory usage
        peak_process_rss = 0
        peak_gpu_allocated = [0] * n_gpu if torch.cuda.is_available() else []
        
        for iter_num in range(args.iterations):
            logger.info(f"Running iteration {iter_num + 1}/{args.iterations}...")
            t0 = time.perf_counter()

            for batch in next(it):             # `batch` is an OrderedDict
                for v in batch.values():
                    # Newer wheels: DALI Tensor ➜ .as_cpu()
                    if hasattr(v, "as_cpu"):
                        v = v.as_cpu()
                    # Older wheels: already a torch.Tensor
                    if isinstance(v, torch.Tensor):
                        v = v.cpu()            # sync to host
                    if hasattr(v, "numpy"):    # final read to ensure timing includes copy
                        _ = v.numpy()
            
            elapsed_ms = (time.perf_counter() - t0) * 1e3
            iteration_times_ms.append(elapsed_ms)
            ms_per_sample = elapsed_ms / samples_per_iter
            logger.info(f"  Iteration {iter_num + 1}: {elapsed_ms:.2f} ms "
                       f"({ms_per_sample:.3f} ms/sample)")
            
            # Track peak memory
            mem_current = get_memory_stats()
            if HAS_PSUTIL and mem_current.get('process_rss_mb', 0) > peak_process_rss:
                peak_process_rss = mem_current['process_rss_mb']
            if 'gpu_allocated_mb' in mem_current:
                for i, alloc in enumerate(mem_current['gpu_allocated_mb']):
                    if alloc > peak_gpu_allocated[i]:
                        peak_gpu_allocated[i] = alloc
        
        # Calculate and display final statistics
        logger.info("")
        logger.info("="*70)
        logger.info("FINAL STATISTICS")
        logger.info("="*70)
        
        times_array = np.array(iteration_times_ms)
        mean_ms = np.mean(times_array)
        std_ms = np.std(times_array)
        min_ms = np.min(times_array)
        max_ms = np.max(times_array)
        median_ms = np.median(times_array)
        
        logger.info(f"Configuration:")
        logger.info(f"  Batch size:    {args.batch}")
        logger.info(f"  GPUs:          {n_gpu}")
        logger.info(f"  Workers:       {args.workers}")
        logger.info(f"  Samples/iter:  {samples_per_iter}")
        logger.info(f"  Iterations:    {args.iterations}")
        logger.info(f"  Record size:   {rec_bytes // 1024} KiB")
        logger.info(f"  O_DIRECT:      {args.direct}")
        logger.info(f"")
        logger.info(f"Time per iteration (ms):")
        logger.info(f"  Mean:          {mean_ms:.2f} ms")
        logger.info(f"  Std Dev:       {std_ms:.2f} ms")
        logger.info(f"  Min:           {min_ms:.2f} ms")
        logger.info(f"  Max:           {max_ms:.2f} ms")
        logger.info(f"  Median:        {median_ms:.2f} ms")
        
        if args.iterations > 1:
            p95_ms = np.percentile(times_array, 95)
            p99_ms = np.percentile(times_array, 99)
            logger.info(f"  95th pctl:     {p95_ms:.2f} ms")
            logger.info(f"  99th pctl:     {p99_ms:.2f} ms")
        
        logger.info(f"")
        logger.info(f"Time per sample (ms):")
        logger.info(f"  Mean:          {mean_ms/samples_per_iter:.3f} ms/sample")
        logger.info(f"  Min:           {min_ms/samples_per_iter:.3f} ms/sample")
        logger.info(f"  Max:           {max_ms/samples_per_iter:.3f} ms/sample")
        
        logger.info(f"")
        logger.info(f"Throughput (samples/sec):")
        logger.info(f"  Mean:          {samples_per_iter/(mean_ms/1000):.1f} samples/sec")
        logger.info(f"  Peak (best):   {samples_per_iter/(min_ms/1000):.1f} samples/sec")
        
        logger.info(f"")
        cache_note = "(actual disk I/O)" if args.drop_cache else "(from binary files, may include page cache)"
        logger.info(f"Bandwidth {cache_note}:")
        mean_bw_mibs = (bytes_per_iter / (1024**2)) / (mean_ms / 1000)
        min_bw_mibs = (bytes_per_iter / (1024**2)) / (max_ms / 1000)  # min bandwidth = max time
        max_bw_mibs = (bytes_per_iter / (1024**2)) / (min_ms / 1000)  # max bandwidth = min time
        
        # Also calculate decimal (MB/s) for comparison with fio
        mean_bw_mbs = (bytes_per_iter / (1000**2)) / (mean_ms / 1000)
        min_bw_mbs = (bytes_per_iter / (1000**2)) / (max_ms / 1000)
        max_bw_mbs = (bytes_per_iter / (1000**2)) / (min_ms / 1000)
        
        logger.info(f"  Data/iter:     {bytes_per_iter / (1024**2):.2f} MiB ({bytes_per_iter / (1000**2):.2f} MB)")
        logger.info(f"  Mean:          {mean_bw_mibs:.2f} MiB/s ({mean_bw_mbs:.2f} MB/s) = {mean_bw_mibs / 1024:.2f} GiB/s")
        logger.info(f"  Min:           {min_bw_mibs:.2f} MiB/s ({min_bw_mbs:.2f} MB/s) = {min_bw_mibs / 1024:.2f} GiB/s")
        logger.info(f"  Peak (best):   {max_bw_mibs:.2f} MiB/s ({max_bw_mbs:.2f} MB/s) = {max_bw_mbs / 1024:.2f} GiB/s")
        
        # Display memory statistics
        logger.info(f"")
        logger.info(f"Memory Usage:")
        mem_final = get_memory_stats()
        
        if HAS_PSUTIL:
            logger.info(f"  Initial Process RSS:  {mem_initial['process_rss_mb']:.2f} MiB")
            logger.info(f"  Final Process RSS:    {mem_final['process_rss_mb']:.2f} MiB")
            logger.info(f"  Peak Process RSS:     {peak_process_rss:.2f} MiB")
            logger.info(f"  System Memory:        {mem_final['system_used_mb']:.2f} / {mem_final['system_total_mb']:.2f} MiB ({mem_final['system_percent']:.1f}%)")
        
        # Only show GPU memory if we're actually using GPU
        if torch.cuda.is_available() and 'gpu_allocated_mb' in mem_final:
            # Check if any GPU memory is actually being used
            gpu_memory_used = any(alloc > 0 for alloc in mem_final['gpu_allocated_mb'])
            if gpu_memory_used:
                for i in range(n_gpu):
                    logger.info(f"  GPU {i} Allocated:     {mem_final['gpu_allocated_mb'][i]:.2f} MiB (peak: {peak_gpu_allocated[i]:.2f} MiB)")
                    logger.info(f"  GPU {i} Reserved:      {mem_final['gpu_reserved_mb'][i]:.2f} MiB / {mem_final['gpu_total_mb'][i]:.2f} MiB total")
        
        logger.info("="*70)
        
    except KeyboardInterrupt:
        logger.info("Benchmark interrupted by user")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Benchmark failed: {e}")
        sys.exit(1)
    finally:
        cleanup_resources()

if __name__ == "__main__":
    main()