#!/usr/bin/env python3
"""
dali_random_read_numpy.py
-------------------------
Random-read benchmark using *.npy* shards generated by create_synthetic_numpy.py
"""

from __future__ import annotations
import argparse, bisect, glob, random, sys, time, logging, atexit
from pathlib import Path
from typing import Sequence

import numpy as np
import torch
from nvidia.dali import fn, pipeline_def, types

try:    # DALI ≥ 1.30
    from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy
except ImportError:
    from nvidia.dali.plugin.base_iterator import DALIGenericIterator
    from nvidia.dali.plugin.pytorch import LastBatchPolicy

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Global resource tracking
_loaded_arrays = []
_pipes = []

def cleanup_resources():
    """Clean up global resources"""
    global _loaded_arrays, _pipes
    logger.info("Cleaning up resources...")
    
    # Clear loaded arrays
    _loaded_arrays.clear()
    
    # Clear pipe references (DALI manages lifecycle automatically)
    _pipes.clear()
    
    logger.info("Resource cleanup completed")

# Register cleanup function
atexit.register(cleanup_resources)


# ---------------------------------------------------------------------------
def open_shards(pattern: str):
    """Open shards with proper error handling and resource tracking"""
    try:
        dirs = sorted(Path(p).parent for p in glob.glob(pattern))
        if not dirs:
            raise FileNotFoundError(f"No matches for pattern: {pattern!r}")
        
        logger.info(f"Found {len(dirs)} shard directories")
        
        imgs, acts, sts, cum = [], [], [], [0]
        for i, d in enumerate(dirs):
            try:
                logger.debug(f"Loading shard {i+1}/{len(dirs)}: {d}")
                
                # Load arrays with error handling
                img_path = d / "image.npy"
                act_path = d / "actions.npy"
                st_path = d / "state.npy"
                
                if not all(p.exists() for p in [img_path, act_path, st_path]):
                    missing = [p.name for p in [img_path, act_path, st_path] if not p.exists()]
                    raise FileNotFoundError(f"Missing files in {d}: {missing}")
                
                img_array = np.load(img_path, mmap_mode="r")
                act_array = np.load(act_path, mmap_mode="r")
                st_array = np.load(st_path, mmap_mode="r")
                
                # Track loaded arrays for cleanup
                _loaded_arrays.extend([img_array, act_array, st_array])
                
                imgs.append(img_array)
                acts.append(act_array)
                sts.append(st_array)
                cum.append(cum[-1] + len(img_array))
                
            except Exception as e:
                logger.error(f"Failed to load shard {d}: {e}")
                raise
        
        logger.info(f"Successfully loaded {len(imgs)} shards with {cum[-1]} total samples")
        return imgs, acts, sts, cum
        
    except Exception as e:
        logger.error(f"Failed to open shards: {e}")
        raise


# ---------------------------------------------------------------------------
class ExternalIterator:
    def __init__(self, imgs, acts, sts, cum, global_idx, bs, rank, world):
        self.imgs, self.acts, self.sts, self.cum = imgs, acts, sts, cum
        start = len(global_idx) * rank // world
        end   = len(global_idx) * (rank + 1) // world
        self.idx = global_idx[start:end]
        self.bs  = bs
        self.n   = len(self.idx)
        self.i   = 0

    def __iter__(self): self.i = 0; return self

    def _fetch(self, g):
        s = bisect.bisect_right(self.cum, g) - 1
        loc = g - self.cum[s]
        return (self.imgs[s][loc],
                self.acts[s][loc],
                self.sts[s][loc])

    def __next__(self):
        if self.i >= self.n: raise StopIteration
        batch = [self._fetch(self.idx[(self.i+k) % self.n]) for k in range(self.bs)]
        self.i += self.bs
        return tuple(map(list, zip(*batch)))

    next = __next__


# ---------------------------------------------------------------------------
@pipeline_def
def pipe(eii, device_read_ahead: int):
    img, act, st = fn.external_source(
        source=eii, num_outputs=3, batch=True,
        dtype=[types.UINT8, types.FLOAT, types.FLOAT])
    return img, act, st


# ---------------------------------------------------------------------------
def main():
    try:
        ap = argparse.ArgumentParser()
        ap.add_argument("--shard", required=True,
                        help='glob "/mnt/weka/shards_numpy/*/image.npy"')
        ap.add_argument("--batch", type=int, default=256)
        ap.add_argument("--workers", type=int, default=4)
        ap.add_argument("--shuffle", action="store_true")
        ap.add_argument("--device-read-ahead", type=int, default=1)
        ap.add_argument("--verbose", "-v", action="store_true", help="Enable verbose logging")
        args = ap.parse_args()

        # Set logging level based on verbosity
        if args.verbose:
            logging.getLogger().setLevel(logging.DEBUG)

        logger.info(f"Starting benchmark with args: {vars(args)}")

        # Open shards with error handling
        imgs, acts, sts, cum = open_shards(args.shard)
        total = cum[-1]
        logger.info(f"📦 {len(imgs)} shards → {total} samples")

        # Prepare indices
        gidx = list(range(total))
        if args.shuffle: 
            random.shuffle(gidx)
            logger.info("Shuffled global indices")

        # Setup GPU configuration
        n_gpu = max(1, torch.cuda.device_count())
        logger.info(f"Using {n_gpu} GPU(s)")

        # Create and build pipes
        pipes = []
        for dev in range(n_gpu):
            try:
                eii = ExternalIterator(imgs, acts, sts, cum, gidx,
                                       args.batch, dev, n_gpu)
                pipe_instance = pipe(batch_size=args.batch,
                                   num_threads=args.workers,
                                   device_id=dev,
                                   eii=eii,
                                   device_read_ahead=args.device_read_ahead)
                pipes.append(pipe_instance)
                _pipes.append(pipe_instance)  # Track for cleanup
            except Exception as e:
                logger.error(f"Failed to create pipe for GPU {dev}: {e}")
                raise

        # Build all pipes
        for i, p in enumerate(pipes):
            try:
                p.build()
                logger.debug(f"Built pipe {i+1}/{len(pipes)}")
            except Exception as e:
                logger.error(f"Failed to build pipe {i}: {e}")
                raise

        # Create iterator
        it = DALIGenericIterator(
            pipes, ["image","actions","state"], size=total,
            last_batch_policy=LastBatchPolicy.PARTIAL, dynamic_shape=True)

        # Warm-up
        logger.info("Running warm-up...")
        next(it)
        
        # Benchmark
        logger.info("Starting benchmark...")
        t0 = time.perf_counter()

        for batch in next(it):             # `batch` is an OrderedDict
            for v in batch.values():
                # Newer wheels: DALI Tensor ➜ .as_cpu()
                if hasattr(v, "as_cpu"):
                    v = v.as_cpu()
                # Older wheels: already a torch.Tensor
                if isinstance(v, torch.Tensor):
                    v = v.cpu()            # sync to host
                if hasattr(v, "numpy"):    # final read to ensure timing includes copy
                    _ = v.numpy()
        
        ms = (time.perf_counter() - t0)*1e3
        logger.info(f"✅ {args.batch*n_gpu} samples in {ms:.2f} ms "
                   f"→ {ms/(args.batch*n_gpu):.3f} ms/sample")
        
    except KeyboardInterrupt:
        logger.info("Benchmark interrupted by user")
        sys.exit(1)
    except Exception as e:
        logger.error(f"Benchmark failed: {e}")
        sys.exit(1)
    finally:
        cleanup_resources()


if __name__ == "__main__":
    main()